export const blocks = {
    header: {
        left: {
            html: `/blocks/header/header-left.html`,
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".header-div",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Top Radius",
                    replace: "$ $ 0px 0px",
                    for: ".header-div",
                    field: "input",
                    default: "30px",
                    inputFault: "30px",
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Logo Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Image Url",
                    for: ".logo-img",
                    field: "input",
                    default: "https://placehold.co/80x50/slateblue/FFF?text=LOGO",
                    inputFault: "https://placehold.co/80x50/slateblue/FFF?text=LOGO",
                    inputChange: ["src"],
                    change: ["src"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Upload",
                    for: ".logo-img",
                    field: "input_file",
                    sizeLimit: 30,
                    inputChange: ["src"],
                    change: ["src"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Width",
                    for: ".logo-img",
                    field: "input",
                    default: "80px",
                    inputFault: "80px",
                    inputChange: ['style', 'width'],
                    change: ['style', 'width'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Height",
                    for: ".logo-img",
                    field: "input",
                    default: "50px",
                    inputFault: "50px",
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Radius",
                    for: ".logo-img",
                    field: "input",
                    default: "5px",
                    inputFault: "5px",
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Text",
                    info: "Please enter the text that will be displayed as the clickable link, one line per link.",
                    for: ".header_links",
                    field: "textarea",
                    inputFault: "Home\nAbout\nContent",
                    default: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;"> Home</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">About</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Contact</a>`,
                    inputChange: ['textContent'],
                    change: ['innerHTML'],
                    createElement: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Link</a>`,
                    keepValues: [["href"], ["style"]],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Url",
                    info: "Please enter the corresponding URL for each link text, one per line.",
                    for: ".header_links",
                    field: "textarea",
                    inputFault: "#insertUrlLink\n#insertUrlLink\n#insertUrlLink",
                    default: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;"> Home</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">About</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Contact</a>`,
                    inputChange: ['href'],
                    change: ['innerHTML'],
                    createElement: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Link</a>`,
                    keepValues: [["innerHTML"], ["style"]],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Font Color",
                    for: ".header_links a",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link FontSize 13px - 24px",
                    for: ".header_links a",
                    field: "input_range",
                    min: 13,
                    max: 24,
                    replace: "$px",
                    default: 13,
                    inputFault: 13,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
            ]
        },
        center: {
            html: `/blocks/header/header-center.html`,
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".header-div",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Top Radius",
                    replace: "$ $ 0px 0px",
                    for: ".header-div",
                    field: "input",
                    default: "30px",
                    inputFault: "30px",
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Logo Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Image Url",
                    for: ".logo-img",
                    field: "input",
                    default: "https://placehold.co/80x50/slateblue/FFF?text=LOGO",
                    inputFault: "https://placehold.co/80x50/slateblue/FFF?text=LOGO",
                    inputChange: ["src"],
                    change: ["src"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Upload",
                    for: ".logo-img",
                    field: "input_file",
                    sizeLimit: 30,
                    inputChange: ["src"],
                    change: ["src"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Width",
                    for: ".logo-img",
                    field: "input",
                    default: "80px",
                    inputFault: "80px",
                    inputChange: ['style', 'width'],
                    change: ['style', 'width'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Height",
                    for: ".logo-img",
                    field: "input",
                    default: "50px",
                    inputFault: "50px",
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Radius",
                    for: ".logo-img",
                    field: "input",
                    default: "5px",
                    inputFault: "5px",
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Text",
                    info: "Please enter the text that will be displayed as the clickable link, one line per link.",
                    for: ".header_links",
                    field: "textarea",
                    inputFault: "Home\nAbout\nContent",
                    default: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;"> Home</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">About</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Contact</a>`,
                    inputChange: ['textContent'],
                    change: ['innerHTML'],
                    createElement: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Link</a>`,
                    keepValues: [["href"], ["style"]],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Url",
                    info: "Please enter the corresponding URL for each link text, one per line.",
                    for: ".header_links",
                    field: "textarea",
                    inputFault: "#insertUrlLink\n#insertUrlLink\n#insertUrlLink",
                    default: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;"> Home</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">About</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Contact</a>`,
                    inputChange: ['href'],
                    change: ['innerHTML'],
                    createElement: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Link</a>`,
                    keepValues: [["innerHTML"], ["style"]],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Font Color",
                    for: ".header_links a",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link FontSize 13px - 24px",
                    for: ".header_links a",
                    field: "input_range",
                    min: 13,
                    max: 24,
                    replace: "$px",
                    default: 13,
                    inputFault: 13,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
            ]
        },
        right: {
            html: `/blocks/header/header-right.html`,
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".header-div",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Top Radius",
                    replace: "$ $ 0px 0px",
                    for: ".header-div",
                    field: "input",
                    default: "30px",
                    inputFault: "30px",
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Logo Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Image Url",
                    for: ".logo-img",
                    field: "input",
                    default: "https://placehold.co/80x50/slateblue/FFF?text=LOGO",
                    inputFault: "https://placehold.co/80x50/slateblue/FFF?text=LOGO",
                    inputChange: ["src"],
                    change: ["src"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Upload",
                    for: ".logo-img",
                    field: "input_file",
                    sizeLimit: 30,
                    inputChange: ["src"],
                    change: ["src"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Width",
                    for: ".logo-img",
                    field: "input",
                    default: "80px",
                    inputFault: "80px",
                    inputChange: ['style', 'width'],
                    change: ['style', 'width'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Height",
                    for: ".logo-img",
                    field: "input",
                    default: "50px",
                    inputFault: "50px",
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Radius",
                    for: ".logo-img",
                    field: "input",
                    default: "5px",
                    inputFault: "5px",
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Text",
                    info: "Please enter the text that will be displayed as the clickable link, one line per link.",
                    for: ".header_links",
                    field: "textarea",
                    inputFault: "Home\nAbout\nContent",
                    default: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;"> Home</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">About</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Contact</a>`,
                    inputChange: ['textContent'],
                    change: ['innerHTML'],
                    createElement: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Link</a>`,
                    keepValues: [["href"], ["style"]],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link Url",
                    info: "Please enter the corresponding URL for each link text, one per line.",
                    for: ".header_links",
                    field: "textarea",
                    inputFault: "#insertUrlLink\n#insertUrlLink\n#insertUrlLink",
                    default: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;"> Home</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">About</a><a href="#insertUrlLink"style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Contact</a>`,
                    inputChange: ['href'],
                    change: ['innerHTML'],
                    createElement: `<a href="#insertUrlLink" style="display:inline-block;color:#000000;font-weight:700;font-family:'Inter','Arial',sans-serif;font-size:13px;line-height:0;text-decoration:none;text-transform:none;padding:0;padding-top:0;padding-left:0;padding-right:8px;padding-bottom:0;text-decoration: none;">Link</a>`,
                    keepValues: [["innerHTML"], ["style"]],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Font Color",
                    for: ".header_links a",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Link FontSize 13px - 24px",
                    for: ".header_links a",
                    field: "input_range",
                    min: 13,
                    max: 24,
                    replace: "$px",
                    default: 13,
                    inputFault: 13,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
            ]
        }
    },
    banner: {
        simple: {
            html: '/blocks/banner/banner-simple.html',
            options: [
                {
                    // Banner Img Url
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Simple Banner Url",
                    for: ".simple_banner",
                    field: "input",
                    default: "/images/banner_simple.png",
                    inputFault: "/images/banner_simple.png",
                    inputChange: ["src"],
                    change: ["src"],
                },
                {
                    // Banner Img File Upload
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Upload",
                    for: ".simple_banner",
                    field: "input_file",
                    sizeLimit: 50,
                    inputChange: ["src"],
                    change: ["src"],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Banner Height",
                    for: ".simple_banner",
                    field: "input",
                    default: "auto",
                    inputFault: "auto",
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "ObjectFit",
                    for: ".simple_banner",
                    field: "input_select",
                    options: ["fill", "contain", "cover", "none", "scale-down"],
                    default: "fill",
                    inputFault: "fill",
                    inputChange: ['style', 'objectFit'],
                    change: ['style', 'objectFit'],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "ObjectPosition",
                    for: ".simple_banner",
                    field: "input_select",
                    options: ["left", "right", "center", "top", "bottom", "top left", "top center", "top right", "center left", "center center", "center right", "bottom left", "bottom center", "bottom right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'objectPosition'],
                    change: ['style', 'objectPosition'],
                },
            ]
        },
        text: {
            html: '/blocks/banner/banner-text.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    // Banner Img Url
                    gridColumn: "span 3",
                    gridRow: "span 2",
                    name: "Image Url",
                    for: ".text_banner",
                    field: "input",
                    replace: "linear-gradient(to right, #00000050, #00000050), url('$') no-repeat center center / cover",
                    default: "/images/banner_simple.png",
                    inputFault: "/images/banner_simple.png",
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Height",
                    for: ".text_banner",
                    field: "input",
                    default: "370px",
                    inputFault: "370px",
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Image Fit",
                    for: ".text_banner",
                    field: "input_select",
                    options: ["fill", "contain", "cover", "none", "scale-down"],
                    default: "cover",
                    inputFault: "cover",
                    inputChange: ['style', 'backgroundSize'],
                    change: ['style', 'backgroundSize'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Image Position",
                    for: ".text_banner",
                    field: "input_select",
                    options: ["left", "right", "center", "top", "bottom", "top left", "top center", "top right", "center left", "center center", "center right", "bottom left", "bottom center", "bottom right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'backgroundPosition'],
                    change: ['style', 'backgroundPosition'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Padding 10px 0 50px",
                    for: ".text_banner",
                    field: "input_range",
                    min: 10,
                    max: 100,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Title Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Title",
                    for: ".text_banner_title",
                    field: "input",
                    default: "The Beauty of Nature",
                    inputFault: "The Beauty of Nature",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_banner_title",
                    field: "input_select",
                    options: ["left", "center", "right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_banner_title",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_banner_title",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title FontSize 30px - 70px",
                    for: ".text_banner_title",
                    field: "input_range",
                    min: 30,
                    max: 70,
                    replace: "$px",
                    default: 50,
                    inputFault: 50,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Paragraph Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Paragraph",
                    for: ".text_banner_para",
                    field: "input",
                    default: "Nature’s serenity calms the mind, its beauty inspires creativity, and every moment spent outdoors reconnects us to life’s essence.",
                    inputFault: "Nature’s serenity calms the mind, its beauty inspires creativity, and every moment spent outdoors reconnects us to life’s essence.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_banner_para",
                    field: "input_select",
                    options: ["left", "center", "right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_banner_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_banner_para",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 15px - 30px",
                    for: ".text_banner_para",
                    field: "input_range",
                    min: 15,
                    max: 30,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
            ]
        },
        text_button: {
            html: '/blocks/banner/banner-text-button.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    // Banner Img Url
                    gridColumn: "span 3",
                    gridRow: "span 2",
                    name: "Image Url",
                    for: ".text_banner",
                    field: "input",
                    replace: "linear-gradient(to right, #00000050, #00000050), url('$') no-repeat center center / cover",
                    default: "/images/banner_simple.png",
                    inputFault: "/images/banner_simple.png",
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Height",
                    for: ".text_banner",
                    field: "input",
                    default: "370px",
                    inputFault: "370px",
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Image Fit",
                    for: ".text_banner",
                    field: "input_select",
                    options: ["fill", "contain", "cover", "none", "scale-down"],
                    default: "cover",
                    inputFault: "cover",
                    inputChange: ['style', 'backgroundSize'],
                    change: ['style', 'backgroundSize'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Image Position",
                    for: ".text_banner",
                    field: "input_select",
                    options: ["left", "right", "center", "top", "bottom", "top left", "top center", "top right", "center left", "center center", "center right", "bottom left", "bottom center", "bottom right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'backgroundPosition'],
                    change: ['style', 'backgroundPosition'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Padding 10px 0 50px",
                    for: ".text_banner",
                    field: "input_range",
                    min: 10,
                    max: 100,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Title Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Title",
                    for: ".text_banner_title",
                    field: "input",
                    default: "The Beauty of Nature",
                    inputFault: "The Beauty of Nature",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_banner_title",
                    field: "input_select",
                    options: ["left", "center", "right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_banner_title",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_banner_title",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title FontSize 30px - 70px",
                    for: ".text_banner_title",
                    field: "input_range",
                    min: 30,
                    max: 70,
                    replace: "$px",
                    default: 50,
                    inputFault: 50,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Paragraph Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Paragraph",
                    for: ".text_banner_para",
                    field: "input",
                    default: "Nature’s serenity calms the mind, its beauty inspires creativity, and every moment spent outdoors reconnects us to life’s essence.",
                    inputFault: "Nature’s serenity calms the mind, its beauty inspires creativity, and every moment spent outdoors reconnects us to life’s essence.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_banner_para",
                    field: "input_select",
                    options: ["left", "center", "right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_banner_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_banner_para",
                    field: "input_color",
                    default: "#ffffff",
                    inputFault: "#ffffff",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 15px - 30px",
                    for: ".text_banner_para",
                    field: "input_range",
                    min: 15,
                    max: 30,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Banner Button Settings",
                    field: "divider",
                    id: "divider_4"
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Button Text",
                    for: ".text_banner_button a",
                    field: "input",
                    default: "Click Here",
                    inputFault: "Click Here",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_banner_button a",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_banner_button a",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Button Alignment",
                    for: ".text_banner_button",
                    field: "input_select",
                    options: ["left", "center", "right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_banner_button a",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 700,
                    inputFault: 700,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Radius",
                    for: ".text_banner_button a",
                    field: "input_range",
                    min: 0,
                    max: 50,
                    replace: "$px",
                    default: 30,
                    inputFault: 30,
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Button FontSize 12px - 30px",
                    for: ".text_banner_button a",
                    field: "input_range",
                    min: 12,
                    max: 30,
                    replace: "$px",
                    default: 14,
                    inputFault: 14,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_4",
                },
            ]
        }

    },
    text: {
        title: {
            html: '/blocks/text/title.html',
            options: [
                {
                    gridColumn: "span 2",
                    gridRow: "span 1",
                    name: "Title Text",
                    for: ".text_title",
                    field: "input",
                    default: "Email Text Title",
                    inputFault: "Email Text Title",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_block_height",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title FontSize 30px - 70px",
                    for: ".text_title",
                    field: "input_range",
                    min: 22,
                    max: 70,
                    replace: "$px",
                    default: 28,
                    inputFault: 28,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_title",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_title",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_title",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Height 100px - 700px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 100,
                    max: 700,
                    replace: "$px",
                    default: 200,
                    inputFault: 200,
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Inline Padding 20px - 300px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 10,
                    max: 300,
                    replace: "10px $px",
                    default: 20,
                    inputFault: 20,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                },
            ]
        },
        title_para: {
            html: '/blocks/text/title-para.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_block_height",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Height 100px - 700px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 100,
                    max: 700,
                    replace: "$px",
                    default: 200,
                    inputFault: 200,
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Inline Padding 20px - 300px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 10,
                    max: 300,
                    replace: "10px $px",
                    default: 20,
                    inputFault: 20,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },

                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title Text",
                    for: ".text_title",
                    field: "input",
                    default: "Email Text Title",
                    inputFault: "Email Text Title",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title FontSize 30px - 70px",
                    for: ".text_title",
                    field: "input_range",
                    min: 22,
                    max: 70,
                    replace: "$px",
                    default: 28,
                    inputFault: 28,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_title",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_title",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_title",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para Text",
                    for: ".text_para",
                    field: "input",
                    default: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputFault: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 12px - 50px",
                    for: ".text_para",
                    field: "input_range",
                    min: 12,
                    max: 50,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_para",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 400,
                    inputFault: 400,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_para",
                    field: "input_color",
                    default: "#777777",
                    inputFault: "#777777",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
            ]
        },
        para: {
            html: '/blocks/text/para.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_block_height",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Height 100px - 700px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 100,
                    max: 700,
                    replace: "$px",
                    default: 140,
                    inputFault: 140,
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Inline Padding 10px - 300px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 10,
                    max: 300,
                    replace: "10px $px",
                    default: 32,
                    inputFault: 32,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para Text",
                    for: ".text_para",
                    field: "input",
                    default: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputFault: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 12px - 50px",
                    for: ".text_para",
                    field: "input_range",
                    min: 12,
                    max: 50,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_para",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "left",
                    inputFault: "left",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 400,
                    inputFault: 400,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_para",
                    field: "input_color",
                    default: "#777777",
                    inputFault: "#777777",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
            ]
        },
        double_para: {
            html: '/blocks/text/double-para.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_block_height",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Height 100px - 700px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 100,
                    max: 700,
                    replace: "$px",
                    default: 140,
                    inputFault: 140,
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Inline Padding 10px - 300px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 10,
                    max: 300,
                    replace: "10px $px",
                    default: 32,
                    inputFault: 32,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Text 1",
                    for: ".text_para_1",
                    field: "input",
                    default: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, eligendi aspernatur repellat suscipit nobis qui voluptatum. Earum velit maxime, quaerat consectetur, error culpa corporis eos voluptatum aliquid illum ducimus numquam.",
                    inputFault: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, eligendi aspernatur repellat suscipit nobis qui voluptatum. Earum velit maxime, quaerat consectetur, error culpa corporis eos voluptatum aliquid illum ducimus numquam.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Text 2",
                    for: ".text_para_2",
                    field: "input",
                    default: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, eligendi aspernatur repellat suscipit nobis qui voluptatum. Earum velit maxime, quaerat consectetur, error culpa corporis eos voluptatum aliquid illum ducimus numquam.",
                    inputFault: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, eligendi aspernatur repellat suscipit nobis qui voluptatum. Earum velit maxime, quaerat consectetur, error culpa corporis eos voluptatum aliquid illum ducimus numquam.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 12px - 50px",
                    for: ".text_para",
                    field: "input_range",
                    min: 12,
                    max: 50,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_para",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "left",
                    inputFault: "left",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 400,
                    inputFault: 400,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_para",
                    field: "input_color",
                    default: "#777777",
                    inputFault: "#777777",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
            ]
        },
        title_para_left: {
            html: '/blocks/text/title-para-left.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_block_height",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Height 100px - 700px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 100,
                    max: 700,
                    replace: "$px",
                    default: 200,
                    inputFault: 200,
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Inline Padding 20px - 300px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 10,
                    max: 300,
                    replace: "10px $px",
                    default: 20,
                    inputFault: 20,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },

                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title Text",
                    for: ".text_title",
                    field: "input",
                    default: "Email Text Title",
                    inputFault: "Email Text Title",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title FontSize 30px - 70px",
                    for: ".text_title",
                    field: "input_range",
                    min: 22,
                    max: 70,
                    replace: "$px",
                    default: 28,
                    inputFault: 28,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_title",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_title",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_title",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para Text",
                    for: ".text_para",
                    field: "input",
                    default: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputFault: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 12px - 50px",
                    for: ".text_para",
                    field: "input_range",
                    min: 12,
                    max: 50,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_para",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 400,
                    inputFault: 400,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_para",
                    field: "input_color",
                    default: "#777777",
                    inputFault: "#777777",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
            ]
        },
        title_para_button: {
            html: '/blocks/text/title-para-button.html',
            options: [
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background Settings",
                    field: "divider",
                    id: "divider_1"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_block_height",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Height 100px - 700px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 100,
                    max: 700,
                    replace: "$px",
                    default: 200,
                    inputFault: 200,
                    inputChange: ['style', 'height'],
                    change: ['style', 'height'],
                    dividerID: "divider_1",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Inline Padding 20px - 300px",
                    for: ".text_block_height",
                    field: "input_range",
                    min: 10,
                    max: 300,
                    replace: "10px $px",
                    default: 20,
                    inputFault: 20,
                    inputChange: ['style', 'padding'],
                    change: ['style', 'padding'],
                    dividerID: "divider_1",
                },

                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title Settings",
                    field: "divider",
                    id: "divider_2"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title Text",
                    for: ".text_title",
                    field: "input",
                    default: "Email Text Title",
                    inputFault: "Email Text Title",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Title FontSize 30px - 70px",
                    for: ".text_title",
                    field: "input_range",
                    min: 22,
                    max: 70,
                    replace: "$px",
                    default: 28,
                    inputFault: 28,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_title",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_title",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 600,
                    inputFault: 600,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_title",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_2",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Paragraph Settings",
                    field: "divider",
                    id: "divider_3"
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para Text",
                    for: ".text_para",
                    field: "input",
                    default: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputFault: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum possimus omnis dicta, maiores sapiente temporibus, asperiores consequatur nihil facere sit laboriosam rerum error animi cum provident laborum id corporis exercitationem.",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Para FontSize 12px - 50px",
                    for: ".text_para",
                    field: "input_range",
                    min: 12,
                    max: 50,
                    replace: "$px",
                    default: 16,
                    inputFault: 16,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Text Alignment",
                    for: ".text_para",
                    field: "input_select",
                    options: ["left", "center", "right",],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_para",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 400,
                    inputFault: 400,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_para",
                    field: "input_color",
                    default: "#777777",
                    inputFault: "#777777",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_3",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Button Settings",
                    field: "divider",
                    id: "divider_4"
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Button Text",
                    for: ".text_button a",
                    field: "input",
                    default: "Click Here",
                    inputFault: "Click Here",
                    inputChange: ['textContent'],
                    change: ['textContent'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Background",
                    for: ".text_button a",
                    field: "input_color",
                    default: "#FFFFFF",
                    inputFault: "#FFFFFF",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "background"],
                    change: ["style", "background"],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Color",
                    for: ".text_button a",
                    field: "input_color",
                    default: "#000000",
                    inputFault: "#000000",
                    colorPath: ["style", "background"],
                    inputChange: ["style", "color"],
                    change: ["style", "color"],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Button Alignment",
                    for: ".text_button",
                    field: "input_select",
                    options: ["left", "center", "right"],
                    default: "center",
                    inputFault: "center",
                    inputChange: ['style', 'textAlign'],
                    change: ['style', 'textAlign'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Font Weight",
                    for: ".text_button a",
                    field: "input_select",
                    options: [400, 500, 600, 700, 800, 900],
                    default: 700,
                    inputFault: 700,
                    inputChange: ['style', 'fontWeight'],
                    change: ['style', 'fontWeight'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 1",
                    gridRow: "span 1",
                    name: "Radius",
                    for: ".text_button a",
                    field: "input_range",
                    min: 0,
                    max: 50,
                    replace: "$px",
                    default: 30,
                    inputFault: 30,
                    inputChange: ['style', 'borderRadius'],
                    change: ['style', 'borderRadius'],
                    dividerID: "divider_4",
                },
                {
                    gridColumn: "span 3",
                    gridRow: "span 1",
                    name: "Button FontSize 12px - 30px",
                    for: ".text_button a",
                    field: "input_range",
                    min: 12,
                    max: 30,
                    replace: "$px",
                    default: 14,
                    inputFault: 14,
                    inputChange: ['style', 'fontSize'],
                    change: ['style', 'fontSize'],
                    dividerID: "divider_4",
                },
            ]
        },
    }
}
